<?xml version="1.0" ?>
<robot name="table" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find component_sorting_description)/urdf/inertia.urdf.xacro" />
  <xacro:include filename="$(find component_sorting_description)/urdf/box/holder.urdf.xacro" />
<!--   <xacro:include filename="$(find vigir_ar_alvar_description)/urdf/artag.urdf.xacro" /> -->
  <xacro:include filename="$(find component_sorting_description)/ar_tags/ar_tag_12cm_border.urdf.xacro" />

  <xacro:arg name="prefix" default="table_"/>
  <xacro:property name="prefix" value="$(arg prefix)" />
  

  <xacro:property name="objects_config_yaml_file" value="$(find component_sorting)/config/objects_config.yaml" />
  <xacro:property name="objects_config" value="${load_yaml(objects_config_yaml_file)}"/>

  <xacro:property name="component_sorting_yaml_file" value="$(find component_sorting)/config/component_sorting.yaml" />
  <xacro:property name="component_sorting" value="${load_yaml(component_sorting_yaml_file)}"/>

  <xacro:arg name="table_length" default="0.63"/>
  <xacro:property name="table_length" value="${objects_config['table']['geometry']['box']['length']}" />

  <xacro:arg name="table_width" default="0.63"/>
  <xacro:property name="table_width" value="${objects_config['table']['geometry']['box']['width']}" />

  <xacro:arg name="table_height" default="0.75"/>
  <xacro:property name="table_height" value="${objects_config['table']['geometry']['box']['height']}" />

  <xacro:arg name="holder_width" default="0.228"/>
  <xacro:property name="holder_width" value="${component_sorting['holder']['width']}" />

  <xacro:arg name="holder_length" default="0.30"/>
  <xacro:property name="holder_length" value="${component_sorting['holder']['length']}" />

  <xacro:arg name="qr_height" default="0.375"/>
  <xacro:property name="qr_height" value="${objects_config['table']['geometry']['qr']['height']}" />
  

  <gazebo>
    <plugin name="${prefix}tf_publisher" filename="librobotnik_gazebo_ground_truth_odom.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50.0</updateRate>
      <bodyName>${prefix}base_link</bodyName> 
      <frameName>${prefix}base_link_gt</frameName> 
      <worldBodyName>world</worldBodyName> 
      <worldFrameName>robot_map</worldFrameName> 
      <topicName>${prefix}tf</topicName>
      <gaussianNoise>0.01</gaussianNoise>
      <xyzOffsets>0 0 0</xyzOffsets>
      <rpyOffsets>0 0 0</rpyOffsets>
      <broadcastTF>True</broadcastTF>
    </plugin>
  </gazebo>

 
  <link name="${prefix}base_link">
    <inertial>
      <mass value="100" />
      <origin xyz="0 0 ${table_height/2}" rpy="0 0 0" />
      <solid_cuboid_inertia m="100" h="${table_height}" d="${table_length}" w="${table_width}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${table_height/2}"/>
      <geometry>
        <box size="${table_length} ${table_width} ${table_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${table_height/2}"/>
      <geometry>
        <box size="${table_length} ${table_width} ${table_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${-table_length/2}  0 ${+qr_height}"/>
    <parent link="${prefix}base_link"/>
    <child link="${prefix}qr"/>
  </joint>

  <link name="${prefix}qr">
  </link>

        <!-- TABLE TAG -->
  <xacro:ar_tag prefix="${prefix}" parent="${prefix}qr" tag_id="marker10_12cm">
      <origin xyz="0 0 0" rpy="0 ${-3.14159/2} 0"/>
  </xacro:ar_tag>

  <xacro:property name="center_holder_offset_x" value="${(holder_length-table_length)/2}"/>
  <xacro:property name="center_holder_offset_y" value="0.0"/>
  <xacro:property name="center_holder_offset_z" value="${table_height}"/> 

  <xacro:property name="left_holder_offset_x" value="${(holder_length-table_length)/2}"/> <!-- -0.195 -->
  <xacro:property name="left_holder_offset_y" value="${holder_width}"/> <!-- 0.225 -->
  <xacro:property name="left_holder_offset_z" value="${table_height}"/>

  <xacro:property name="right_holder_offset_x" value="${(holder_length-table_length)/2}"/>
  <xacro:property name="right_holder_offset_y" value="${-holder_width}"/>
  <xacro:property name="right_holder_offset_z" value="${table_height}"/>


    <!-- HOLDERS -->
  <xacro:holder prefix="${prefix}center_" parent="${prefix}base_link" tag_id="marker2_12cm" >
      <origin xyz="${center_holder_offset_x} ${center_holder_offset_y} ${center_holder_offset_z}" rpy="0 0 0"/>
  </xacro:holder>

  <xacro:holder prefix="${prefix}left_" parent="${prefix}base_link" tag_id="marker3_12cm" >
      <origin xyz="${left_holder_offset_x} ${left_holder_offset_y} ${left_holder_offset_z}" rpy="0 0 0"/>
  </xacro:holder>

  <xacro:holder prefix="${prefix}right_" parent="${prefix}base_link" tag_id="marker1_12cm" >
      <origin xyz="${right_holder_offset_x} ${right_holder_offset_y} ${right_holder_offset_z}" rpy="0 0 0"/>
  </xacro:holder>

  <gazebo reference="${prefix}base_link">
    <material>Gazebo/White</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <static>true</static>

  </gazebo>




</robot>
