<?xml version="1.0" ?>
<robot name="table" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find component_sorting_description)/urdf/inertia.urdf.xacro" />
  <xacro:include filename="$(find component_sorting_description)/urdf/box/holder_table.urdf.xacro" />

  <xacro:arg name="prefix" default="table_"/>
  <xacro:property name="prefix" value="$(arg prefix)" />

  <xacro:property name="table_length" value="0.63" />
  <xacro:property name="table_width" value="0.63" />
  <xacro:property name="table_height" value="0.75" />
  <xacro:property name="holder_width" value="0.228" />
  <xacro:property name="qr_height" value="0.40" />
  

  <gazebo>
    <plugin name="${prefix}tf_publisher" filename="librobotnik_gazebo_ground_truth_odom.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50.0</updateRate>
      <bodyName>${prefix}qr</bodyName> 
      <frameName>${prefix}qr_tf</frameName> 
      <worldBodyName>world</worldBodyName> 
      <worldFrameName>robot_map</worldFrameName> 
      <topicName>${prefix}tf</topicName>
      <gaussianNoise>0.01</gaussianNoise>
      <xyzOffsets>0 0 0</xyzOffsets>
      <rpyOffsets>0 0 0</rpyOffsets>
      <broadcastTF>True</broadcastTF>
    </plugin>
  </gazebo>


  <link name="${prefix}qr">
    <inertial>
      <mass value="40" />
      <origin xyz="${table_length/2} 0 ${table_height/2-qr_height}" />
      <solid_cuboid_inertia m="20" h="${table_height}" d="0.63" w="0.63"/>
    </inertial>
    <visual>
      <origin xyz="${table_length/2} 0 ${table_height/2-qr_height}"/>
      <geometry>
        <box size="${table_length} ${table_width} ${table_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${table_length/2} 0 ${table_height/2-qr_height}"/>
      <geometry>
        <box size="${table_length} ${table_width} ${table_height}" />
      </geometry>
      </collision>
  </link>


  <xacro:property name="center_holder_offset_x" value="0.15"/>
  <xacro:property name="center_holder_offset_y" value="0.0"/>
  <xacro:property name="center_holder_offset_z" value="0.35"/> 

  <xacro:property name="left_holder_offset_x" value="0.15"/> <!-- -0.195 -->
  <xacro:property name="left_holder_offset_y" value="0.228"/> <!-- 0.225 -->
  <xacro:property name="left_holder_offset_z" value="0.35"/>

  <xacro:property name="right_holder_offset_x" value="0.15"/>
  <xacro:property name="right_holder_offset_y" value="-0.228"/>
  <xacro:property name="right_holder_offset_z" value="0.35"/>

    <!-- HOLDERS -->
  <xacro:holder_table prefix="${prefix}center_" parent="${prefix}qr">
      <origin xyz="${center_holder_offset_x} ${center_holder_offset_y} ${center_holder_offset_z}" rpy="0 0 0"/>
  </xacro:holder_table>

  <xacro:holder_table prefix="${prefix}left_" parent="${prefix}qr">
      <origin xyz="${left_holder_offset_x} ${left_holder_offset_y} ${left_holder_offset_z}" rpy="0 0 0"/>
  </xacro:holder_table>

  <xacro:holder_table prefix="${prefix}right_" parent="${prefix}qr">
      <origin xyz="${right_holder_offset_x} ${right_holder_offset_y} ${right_holder_offset_z}" rpy="0 0 0"/>
  </xacro:holder_table>

  <gazebo reference="${prefix}">
    <material>Gazebo/Grey</material>
  </gazebo>
 

</robot>
