# frame to which input is transformed
robot_base_frame: robot_base_link
# frame in which output is published
fixed_frame: robot_odom
# output frame. if locator is able to provide id, this will be 
object_frame: arm_noisy_marker
# from which topic read the image stream
input_topic_name: /arm_rgbd_camera/rgb/image
# from which topic read the camera calibration
camera_info_topic_name: /arm_rgbd_camera/rgb/camera_info 
# marker size, in m

robot_sensor_frame: robot_arm_rgbd_camera_rgb_optical_frame
marker_size: 0.12

# to specify special characteristics for some markers
# still no read by alvar_camera_locator 
markers:

  - id_type: single
    id: 9
    exact_name: box_1_grab_qr
    size: 0.06
    filter_tag: noisy_

  - id_type: single
    id: 8
    exact_name: box_2_grab_qr
    size: 0.06
    filter_tag: noisy_    
  
  - id_type: single
    id: 7
    exact_name: box_3_grab_qr
    size: 0.06
    filter_tag: noisy_    
  


