global_costmap:
  global_frame: $(arg prefix)map
  robot_base_frame: $(arg prefix)base_link
  update_frequency: 5.0
  # robot radius +safety_delta 0.25 + 0.02
  # set to permit drawing a trajectory through the narrowest door
  inflation_radius: 0.20  
  width: 50.0 #5
  height: 50.0 #5
  origin_x: -25.0
  origin_y: -25.0
  resolution: 0.05
  #rolling_window: true
  #plugins: {}
#  - {name: static_layer,        type: "costmap_2d::StaticLayer" }
#
#  static_layer:
#    enabled: false  
  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"

  obstacle_layer:
    enabled: false

