# An action for scanning holder qr position (in the robot or in the table)

# The name of the location from where to scan holder position
string[] position
---
# If scanning was succesful
bool success

# Some informational message
string message
---

# The internal state that the scan action currently is in
string state
