# An action for picking up an object from a location (in the robot or in the table)

# The name of the location from where to pick up 
string from
---
# If pickup was succesful
bool success

# Some informational message
string message
---

# The internal state that the pickup action currently is in
string state
