#Move_group node parameters 
group_name: arm
move_group_timeout: 500 

#Execution mode (wait to receive input from hololens)
wait: false

#Disassembly operation
disassembly : true

#Robot setup
end_effector_link: robot_vgc10_vgc10_link
robot_link: robot_base_footprint

#MoveIt warehouse parameters 
host: "localhost"
port: 33829

#Environment description parameters
holder: #Used in table urdf to locate holders at a standard distance
  width: 0.228
  length: 0.30 

box: #Used to locate boxes in the Region of Interest
  width: 0.25
  length: 0.32

box_handle_displacement: 0.04 #Used to recreate box/handle behaviour during transport in MoveIt

#MoveIt constraint
moveit_constraint: "" #Motion planning constraint to be used

simulation: false 

#Gripper IO
multi_pin: false
#pin_1: 4 
#pin_2: 5
pin_1: 999
pin_2: 999

#Moveit velocity
scale_vel: 0.1
scale_acc: 0.5

#Watchdog of the box detection 
box_tf_watchdog: 6.0
