#Move_group node parameters 
group_name: arm
move_group_timeout: 10 

#Robot setup
end_effector_link: robot_vgc10_vgc10_link
robot_link: robot_base_footprint

#MoveIt warehouse parameters 
host: "localhost"
port: 33829

#Environment description parameters
holder: #Used in table urdf to locate holders at a standard distance
  width: 0.228
  length: 0.30 

box: #Used to locate boxes in the Region of Interest
  width: 0.25
  length: 0.32

box_handle_displacement: 0.04 #Used to recreate box/handle behaviour during transport in MoveIt

#MoveIt constraint
moveit_constraint: "elbow_up" #Motion planning constraint to be used

simulation: true 

#Gripper IO
multi_pin: false
pin_1: 4
pin_2: 4

#Moveit velocity
scale_vel: 0.5

