objects:
#  - holder_robot_right
#  - holder_robot_left
#  - holder_robot_center
#  - holder_table_right
#  - holder_table_left
#  - holder_table_center
#  - box_right
#  - box_left
#  - box_center
#  - handle_right
#  - handle_left
#  - handle_center 
  - table
  - table_1
  - table_2
  - safety_box
  - safety_box_handle
  - box
  - handle 
  - cooler 
  - psu
  - pc_tower
  - disassembly_wall
  - disassembly_table

safety_box:
  spawn: true
  frame_id: robot_center_holder_link
  geometry:
    box:
      height: 0.11
      width: 0.69
      length: 0.31
  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy  

safety_box_handle:
  spawn: true
  frame_id: robot_center_holder_link
  geometry:
    box:
      height: 0.12
      width: 0.69
      length: 0.12
  pose: [[0.0,0.0,0.18],[0.0,0.0,0.0]] # xyz, rpy  

table:
  spawn: false
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.85
      width: 0.63
      length: 0.63
    qr:
      height: 0.365
  pose: [[0.865,0.0,0.425],[0.0,0.0,0.0]] # xyz, rpy

disassembly_table:
  spawn: true
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.40 # 0.85
      width: 0.90
      length: 0.70
  pose: [[0.865,0.0,0.20],[0.0,0.0,0.0]] # xyz, rpy  

table_1:
  spawn: false
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.70 # 0.85
      width: 0.63
      length: 0.63
  pose: [[0.865,0.0,0.425],[0.0,0.0,0.0]] # xyz, rpy

table_2:
  spawn: false
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.81
      width: 0.63
      length: 0.63
  pose: [[0.865,0.0,0.405],[0.0,0.0,0.0]] # xyz, rpy

box:
  spawn: false
  frame_id: ""
  geometry:
    box:
      height: 0.11
      width: 0.19
      length: 0.29
  pose: [[0.0,0.0,0.171],[0.0,3.1416,1.5708]] # xyz, rpy

handle:
  spawn: false
  frame_id: ""
  pose: [[0.0,0.0,0.096],[0.0,3.1416,1.5708]] # xyz, rpy
  geometry:
    box:
      height: 0.20
      width: 0.21
      length: 0.12

cooler:
  spawn: false
  frame_id: ""
  pose: [[-0.17,0.136,0.08],[0.0,0.0,0.0]] # xyz, rpy 0.08 + 0.03 para no contactar
  geometry:
    box:
      height: 0.085
      width: 0.07
      length: 0.1

psu:
  spawn: false
  frame_id: ""
  pose: [[-0.20,0.046,0.1],[0.0,0.0,0.0]] # xyz, rpy 0.07 + 0.03 para no contactar
  geometry:
    box:
      height: 0.095
      width: 0.07
      length: 0.175

pc_tower:
  spawn: false
  frame_id: ""
  pose: [[0.0,0.20,0.1],[0.0,0.0,0.0]] # xyz, rpy 0.07 + 0.03 para no contactar
  geometry:
    box:
      height: 0.19
      width: 0.45
      length: 0.18      

disassembly_wall:
  spawn: false
  frame_id: "robot_base_footprint"
  pose: [[0.35,0.54,0.95],[0.0,0.0,0.0]] # xyz, rpy 0.07 + 0.03 para no contactar
  geometry:
    box:
      height: 1.5
      width: 0.01
      length: 2.0    


  
holder_table_demo:
  spawn: true
  frame_id: robot_base_footprint
  pose: [[1.015,0.0,0.845],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_table_right:
  spawn: true
  frame_id: table_right_holder_link
  pose: [[0.0,0.0,-0.01],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_table_left:
  spawn: true
  frame_id: table_left_holder_link
  pose: [[0.0,0.0,-0.01],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_table_center:
  spawn: true
  frame_id: table_center_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_robot_right:
  spawn: true
  frame_id: robot_right_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_robot_left:
  spawn: true
  frame_id: robot_left_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_robot_center:
  spawn: true
  frame_id: robot_center_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"


box_center:
  spawn: false
  frame_id: table_center_holder_link
  pose: [[0.0,0.0,0.01],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_base.stl"

#box_right:
#  spawn: true
#  frame_id: table_right_holder_link
#  pose: [[0.0,0.0,0.01],[0.0,0.0,0.0]] # xyz, rpy
#  geometry:
#    mesh: "package://component_sorting_description/meshes/box/box_base.stl"

#box_left:
#  spawn: true 
#  frame_id: table_left_holder_link
#  pose: [[0.0,0.0,0.01],[0.0,0.0,0.0]] # xyz, rpy
#  geometry:
#    mesh: "package://component_sorting_description/meshes/box/box_base.stl"

box_left:
  spawn: true
  frame_id: table_left_holder_link
  geometry:
    box:
      height: 0.11
      width: 0.19
      length: 0.29
  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy

#box_center:
#  spawn: true
#  frame_id: table_center_holder_link
#  geometry:
#    box:
#      height: 0.11
#      width: 0.19
#      length: 0.29
#  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy

box_right:
  spawn: true
  frame_id: table_right_holder_link
  geometry:
    box:
      height: 0.11
      width: 0.19
      length: 0.29
  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy

handle_center:
  spawn: true
  frame_id: table_center_holder_link
  pose: [[0.0,0.0,0.08],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"

handle_right:
  spawn: true
  frame_id: table_right_holder_link
  pose: [[0.0,0.0,0.08],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"

handle_left:
  spawn: true
  frame_id: table_left_holder_link
  pose: [[0.0,0.0,0.08],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"

