objects:
#  - holder_robot_right
#  - holder_robot_left
#  - holder_robot_center
#  - holder_table_right
#  - holder_table_left
#  - holder_table_center
#  - box_right
#  - box_left
#  - box_center
#  - handle_right
#  - handle_left
#  - handle_center 
  - table
  - table_1
  - table_2
  - safety_box
  - safety_box_handle
  - box
  - handle 

safety_box:
  spawn: true
  frame_id: robot_center_holder_link
  geometry:
    box:
      height: 0.11
      width: 0.69
      length: 0.31
  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy  

safety_box_handle:
  spawn: true
  frame_id: robot_center_holder_link
  geometry:
    box:
      height: 0.12
      width: 0.69
      length: 0.12
  pose: [[0.0,0.0,0.18],[0.0,0.0,0.0]] # xyz, rpy  

table:
  spawn: false
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.85
      width: 0.63
      length: 0.63
    qr:
      height: 0.365
  pose: [[0.865,0.0,0.425],[0.0,0.0,0.0]] # xyz, rpy

table_1:
  spawn: false
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.85
      width: 0.63
      length: 0.63
  pose: [[0.865,0.0,0.425],[0.0,0.0,0.0]] # xyz, rpy

table_2:
  spawn: false
  frame_id: robot_base_footprint
  geometry:
    box:
      height: 0.81
      width: 0.63
      length: 0.63
  pose: [[0.865,0.0,0.405],[0.0,0.0,0.0]] # xyz, rpy

box:
  spawn: false
  frame_id: ""
  geometry:
    box:
      height: 0.11
      width: 0.19
      length: 0.29
  pose: [[0.0,0.0,0.171],[0.0,3.1416,1.5708]] # xyz, rpy

handle:
  spawn: false
  frame_id: ""
  pose: [[0.0,0.0,0.156],[0.0,3.1416,1.5708]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"  



  
holder_table_demo:
  spawn: true
  frame_id: robot_base_footprint
  pose: [[1.015,0.0,0.845],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_table_right:
  spawn: true
  frame_id: table_right_holder_link
  pose: [[0.0,0.0,-0.01],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_table_left:
  spawn: true
  frame_id: table_left_holder_link
  pose: [[0.0,0.0,-0.01],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_table_center:
  spawn: true
  frame_id: table_center_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_robot_right:
  spawn: true
  frame_id: robot_right_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_robot_left:
  spawn: true
  frame_id: robot_left_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

holder_robot_center:
  spawn: true
  frame_id: robot_center_holder_link
  pose: [[0.0,0.0,0.0],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"


box_center:
  spawn: false
  frame_id: table_center_holder_link
  pose: [[0.0,0.0,0.01],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/box_base.stl"

#box_right:
#  spawn: true
#  frame_id: table_right_holder_link
#  pose: [[0.0,0.0,0.01],[0.0,0.0,0.0]] # xyz, rpy
#  geometry:
#    mesh: "package://component_sorting_description/meshes/box/box_base.stl"

#box_left:
#  spawn: true 
#  frame_id: table_left_holder_link
#  pose: [[0.0,0.0,0.01],[0.0,0.0,0.0]] # xyz, rpy
#  geometry:
#    mesh: "package://component_sorting_description/meshes/box/box_base.stl"

box_left:
  spawn: true
  frame_id: table_left_holder_link
  geometry:
    box:
      height: 0.11
      width: 0.19
      length: 0.29
  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy

#box_center:
#  spawn: true
#  frame_id: table_center_holder_link
#  geometry:
#    box:
#      height: 0.11
#      width: 0.19
#      length: 0.29
#  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy

box_right:
  spawn: true
  frame_id: table_right_holder_link
  geometry:
    box:
      height: 0.11
      width: 0.19
      length: 0.29
  pose: [[0.0,0.0,0.065],[0.0,0.0,0.0]] # xyz, rpy

handle_center:
  spawn: true
  frame_id: table_center_holder_link
  pose: [[0.0,0.0,0.08],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"

handle_right:
  spawn: true
  frame_id: table_right_holder_link
  pose: [[0.0,0.0,0.08],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"

handle_left:
  spawn: true
  frame_id: table_left_holder_link
  pose: [[0.0,0.0,0.08],[0.0,0.0,0.0]] # xyz, rpy
  geometry:
    mesh: "package://component_sorting_description/meshes/box/handle.stl"

