positions_to_use:
  - robot_left
  - robot_center
  - robot_right
  - table_right
  - table_center
  - table_left
  - table_demo


robot_left:
  approach_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]] 
  place_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    #frame_id: robot_left_holder_oriented_link
    #pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.215],[0.0, +3.14159, -3.14159]]
  pick_pose:
    #frame_id: robot_left_holder_oriented_link
    #pose: [[0.0, 0.0, -0.375],[0.0, 0.0, 0.0]] 
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.148],[0.0, +3.14159, -3.14159]]

robot_center:
  approach_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]]
  pre_place_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    #frame_id: robot_center_holder_oriented_link
    #pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.215],[0.0, +3.14159, -3.14159]]
  pick_pose:
    #frame_id: robot_center_holder_oriented_link
    #pose: [[0.0, 0.0, -0.375],[0.0, 0.0, 0.0]]
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.148],[0.0, +3.14159, -3.14159]]   

robot_right:
  approach_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]]
  pre_place_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    #frame_id: robot_right_holder_oriented_link
    #pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.215],[0.0, +3.14159, -3.14159]]
  pick_pose:
    #frame_id: robot_right_holder_oriented_link
    #pose: [[0.0, 0.0, -0.375],[0.0, 0.0, 0.0]]
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.148],[0.0, +3.14159, -3.14159]]  

table_right:
  approach_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.215],[0.0, +3.14159, -3.14159]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.148],[0.0, +3.14159, -3.14159]] 

table_center:
  approach_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.215],[0.0, +3.14159, -3.14159]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.148],[0.0, +3.14159, -3.14159]]

table_left:
  approach_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy  
  pre_place_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]     
  place_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]  
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.215],[0.0, +3.14159, -3.14159]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.01, 0.0, 0.148],[0.0, +3.14159, -3.14159]] 

table_demo:
  approach_pose:
    frame_id: prueba
    pose: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]] # xyz, rpy  



#holder_qr_frames:
#  robot_center:
#    frame_id: robot_center_holder_qr
#
#  robot_right:
#    frame_id: robot_right_holder_qr
#
#  robot_left:
#    frame_id: robot_left_holder_qr
#
#  table_center:
#    frame_id: table_center_holder_qr
#
#  table_right:
#    frame_id: table_right_holder_qr
#  
#  table_left:
#    frame_id: table_left_holder_qr





