positions_to_use:
  - robot_left
  - robot_center
  - robot_right
  - table
  - detection


robot_left:
  approach_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]] 
  place_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: robot_left_grab_link
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]] 

robot_center:
  approach_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]]
  pre_place_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: robot_center_grab_link
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]]


robot_right:
  approach_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]]
  pre_place_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: robot_right_holder_oriented_pose
    link: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: robot_right_grab_link
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]]

table:
  approach_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.297, -0.55],[0.52, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.20],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]]

detection:
  approach_pose:
    frame_id: robot_base_footprint
    pose: [[0.379, 0.035, 1.179],[-2.145, 0.0, -1.478]] # xyz, rpy

   





table_right:
  approach_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.215],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]] 

table_center:
  approach_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.215],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]]

table_left:
  approach_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy  
  pre_place_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]     
  place_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]  
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.215],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]] 

table_demo:
  approach_pose:
    frame_id: prueba
    pose: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]] # xyz, rpy  



#holder_qr_frames:
#  robot_center:
#    frame_id: robot_center_holder_qr
#
#  robot_right:
#    frame_id: robot_right_holder_qr
#
#  robot_left:
#    frame_id: robot_left_holder_qr
#
#  table_center:
#    frame_id: table_center_holder_qr
#
#  table_right:
#    frame_id: table_right_holder_qr
#  
#  table_left:
#    frame_id: table_left_holder_qr





