positions_to_use:
  - robot_left
  - robot_center
  - robot_right
  - table
  - detection
  - psu
  - cooler
  - cooler_fail
  - capacitor_fail
  - back_fail
  - cover
  - capacitor 


robot_left:
  approach_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]] 
  place_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: robot_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: robot_left_grab_link
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]] 

robot_center:
  approach_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]]
  pre_place_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: robot_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: robot_center_grab_link
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]]


robot_right:
  approach_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.079, -0.70],[0.0, 0.0, 0.0]]
  pre_place_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: robot_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.70],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: robot_right_grab_link
    pose: [[0.0, 0.0, -0.147],[0.0, 0.0, 0.0]]

table:
  approach_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.297, -0.55],[0.52, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.036, -0.189, -0.442],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.036, -0.189, -0.422],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.015, -0.22],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.015, -0.118],[0.0, 0.0, 0.0]]
psu:
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[0.845, -0.218, 1.124],[3.088, 0.0, -1.140]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[0.845, -0.218, 0.824],[3.088, 0.0, -1.140]]
#  pre_pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.256, 0.087, -0.473],[0.0, 0.0, -0.565]]
#  pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.256, 0.087, -0.163],[0.0, 0.0, -0.565]]
  pre_pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.200, 0.046, -0.470],[0.0, 0.0, -0.435]]
  pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.200, 0.046, -0.160],[0.0, 0.0, -0.565]]

capacitor:
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[0.276, -0.631, 1.370],[-3.086, -0.026, 3.138]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[0.276, -0.619, 0.759],[-3.122, 0.023, 3.036]]
#  pre_pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.256, 0.087, -0.473],[0.0, 0.0, -0.565]]
#  pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.256, 0.087, -0.163],[0.0, 0.0, -0.565]]
  pre_pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.180, 0.128, -0.469],[0.0, 0.0, 1.507]]
  pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.180, 0.128, -0.169],[0.0, 0.0, 1.507]]

 
cover:
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[-0.0, -0.631, 1.370],[-3.086, -0.026, 3.138]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[-0.10, -0.661, 0.886],[-3.123, -0.026, 3.139]]
#  pre_pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.256, 0.087, -0.473],[0.0, 0.0, -0.565]]
#  pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.256, 0.087, -0.163],[0.0, 0.0, -0.565]]
  pre_pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.123, 0.009, -0.448],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.123, 0.009, -0.138],[0.0, 0.0, 0.0]]   

cooler:
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[0.686, -0.218, 1.124],[3.088, 0.0, -1.140]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[0.686, -0.218, 0.824],[3.088, 0.0, -1.140]] #x: 0.714
#  pre_pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.228, 0.171, -0.478],[0.0, 0.0, -0.535]]  # 10cm away
#  pick_pose:
#    frame_id: pc_tower_qr
#    pose: [[-0.228, 0.171, -0.168],[0.0, 0.0, -0.535]] #-0.178
  pre_pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.175, 0.136, -0.470],[0.0, 0.0, -0.435]]  # 10cm away
  pick_pose:
    frame_id: pc_tower_qr
    pose: [[-0.175, 0.136, -0.160],[0.0, 0.0, -0.435]] #-0.178

capacitor_fail:
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[0.636, -0.473, 1.118],[3.106, 0.023, -1.562]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[0.636, -0.473, 0.918],[3.106, 0.023, -1.562]] #x: 0.714    


cooler_fail:
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[0.533, -0.517, 1.124],[-3.134, -0.0, -1.597]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[0.533, -0.517, 0.824],[-3.134, -0.0, -1.597]] #x: 0.714    

back_fail:
  approach_pose:
    frame_id: robot_base_footprint
    pose: [[-0.581, 0.061, 1.124],[-3.136, 0.005, 1.611]]
  pre_place_pose:
    frame_id: robot_base_footprint
    pose: [[-0.581, 0.061, 1.124],[-3.136, 0.005, 1.611]]
  place_pose:
    frame_id: robot_base_footprint
    pose: [[-0.581, 0.061, 1.051],[-3.136, 0.005, 1.611]] #x: 0.714    

detection:
  approach_pose:
    frame_id: robot_base_footprint
    pose: [[0.379, 0.035, 1.179],[-2.145, 0.0, -1.478]] # xyz, rpy

table_right:
  approach_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_right_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.215],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]] 

table_center:
  approach_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy
  pre_place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]
  place_pose:
    frame_id: table_center_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.215],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]]

table_left:
  approach_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.55],[0.0, 0.0, 0.0]] # xyz, rpy  
  pre_place_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.50],[0.0, 0.0, 0.0]]     
  place_pose:
    frame_id: table_left_holder_oriented_link
    pose: [[0.0, 0.0, -0.423],[0.0, 0.0, 0.0]]  
  pre_pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.215],[0.0, 0.0, 0.0]]
  pick_pose:
    frame_id: box_grab_qr
    pose: [[0.0, 0.0, -0.148],[0.0, 0.0, 0.0]] 

table_demo:
  approach_pose:
    frame_id: prueba
    pose: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]] # xyz, rpy  



#holder_qr_frames:
#  robot_center:
#    frame_id: robot_center_holder_qr
#
#  robot_right:
#    frame_id: robot_right_holder_qr
#
#  robot_left:
#    frame_id: robot_left_holder_qr
#
#  table_center:
#    frame_id: table_center_holder_qr
#
#  table_right:
#    frame_id: table_right_holder_qr
#  
#  table_left:
#    frame_id: table_left_holder_qr





