# Box description
box:
  spawn: true
  static: false
  frame_id: table
  pose: [[0.7,1.6,0.46],[0,0,1.5708]] # xyz, rpy
  geometry:
    box:
      width: 0.15
      length: 0.25 
      height: 0.10
  layout: 
    x: 1
    y: 1 # 2
    z: 3 


# Table
table:
  spawn: true
  static: true
  frame_id: robot_map # moveit frame id
  geometry:
    box:
      height: 0.50
      width: 1.5
      length: 1
    qr:
      height: 0.37  
  pose: [[2,0,0.0],[0.0,0.0,0.0]] # xyz, rpy to  moveit's frame_id 
